### PR TITLE
Updated iconography, app icon

### PR DESCRIPTION
**Pull request by sefsh**

### CODE REVIEW

**Comment by SteveBell** [comment]
Hey yusf, great hearing from you! Please excuse the slow response. The small icons are a nice improvement, thanks for that. Regarding the app icon, we think it still needs some tweaking:

- [ ] use gradient and different colors on keys to make them look more shiny
- [ ] the way the ring is tilted seems to be benefitial on the default OS X keychain solution. In your proposal it is tilted away from the looking person, which seems not ideal.
- [ ] the keys and the chip seem to be very flat and unnatural. can't put my finger on it, but the round badge seems off somehow
- [ ] The shadows on the golden key seem to be a bit too much while the shadow of the keyring and the key ring itself could be a bit stronger
- [ ] as for the badge: could you use the colors from the lock icon we use? also having that a bit more shiny would be nice.
lock icon

That should get us started. Let me know what you think, if you disagree, please raise your concerns. It would be great to bring the app icon into modern times. Then again in a few weeks, we'll have the first 10.12 preview. Would be interesting to see where apple is going and if the OS X keychain icon will be updated. So maybe waiting a bit isn't the worst idea.

For some inspiration here's the current OS X keychain icon on 10.11
keychain

**Comment by yusf** [comment]
Hey Steve! I don't mind the slow pace. This is great feedback, I'll start tweaking the icon when I get around to it. That will probably take a few weeks anyway, so let's see what Apple has in store for the future.

**Comment by themovement919** [comment]
Is there any experts that have knowledge about keychain that could possible help me with my problem?

**Comment by SteveBell** [comment]
@themovement919 this is not a support tracker. Support is here: https://gpgtools.tenderapp.com

**Comment by SteveBell** [comment]
closing, let's continue to use the current icon for now. we can re-open anytime.

**Pull request closed without merging**
